In [1]:
# Import Numpy & PyTorch
import numpy as np
import torch

## Linear Regression Model using PyTorch built-ins

Let's re-implement the same model using some built-in functions and classes from PyTorch.

And now using two different targets: Apples and Oranges

In [2]:
# Imports
import torch.nn as nn

In [3]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [4]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

### Dataset and DataLoader

We'll create a `TensorDataset`, which allows access to rows from `inputs` and `targets` as tuples. We'll also create a DataLoader, to split the data into batches while training. It also provides other utilities like shuffling and sampling.

In [5]:
# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader

In [6]:
# Define dataset
dataset = torch.utils.data.TensorDataset(inputs, targets)

In [7]:
# Define data loader
dataloader = torch.utils.data.DataLoader(dataset, batch_size=5)

### nn.Linear
Instead of initializing the weights & biases manually, we can define the model using `nn.Linear`.

In [8]:
# Define model
model = nn.Linear(inputs.shape[1], targets.shape[1])
model.parameters()

<generator object Module.parameters at 0x7f551d390e50>

### Optimizer
Instead of manually manipulating the weights & biases using gradients, we can use the optimizer `optim.SGD`.

In [9]:
# Define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=1e-4)

### Loss Function
Instead of defining a loss function manually, we can use the built-in loss function `mse_loss`.

In [10]:
# Import nn.functional
import torch.nn.functional as F

In [11]:
# Define loss function
loss_fn = F.mse_loss

In [ ]:
#loss = loss_fn(? , ?)
#print(loss)

### Train the model

We are ready to train the model now. We can define a utility function `fit` which trains the model for a given number of epochs.

In [21]:
# Define a utility function to train the model
def fit(num_epochs, model, loss_fn, opt):
  for epoch in range(num_epochs):
    for xb,yb in dataloader:
      # Generate predictions
      pred = model(xb)
      loss = loss_fn(yb,pred)
      # Perform gradient descent
      loss.backward()
      opt.step()
      opt.zero_grad()
      print('Training loss: ', loss_fn(model(inputs), targets))

In [22]:
# Train the model for 100 epochs
fit(120 , model , loss_fn, optimizer)

Training loss:  tensor(8113.3325, grad_fn=<MseLossBackward>)
Training loss:  tensor(5154.9639, grad_fn=<MseLossBackward>)
Training loss:  tensor(3294.7192, grad_fn=<MseLossBackward>)
Training loss:  tensor(2122.6189, grad_fn=<MseLossBackward>)
Training loss:  tensor(1382.0375, grad_fn=<MseLossBackward>)
Training loss:  tensor(912.3070, grad_fn=<MseLossBackward>)
Training loss:  tensor(612.8047, grad_fn=<MseLossBackward>)
Training loss:  tensor(420.4847, grad_fn=<MseLossBackward>)
Training loss:  tensor(295.8214, grad_fn=<MseLossBackward>)
Training loss:  tensor(214.0140, grad_fn=<MseLossBackward>)
Training loss:  tensor(159.4824, grad_fn=<MseLossBackward>)
Training loss:  tensor(122.4223, grad_fn=<MseLossBackward>)
Training loss:  tensor(96.6505, grad_fn=<MseLossBackward>)
Training loss:  tensor(78.2548, grad_fn=<MseLossBackward>)
Training loss:  tensor(64.7494, grad_fn=<MseLossBackward>)
Training loss:  tensor(54.5452, grad_fn=<MseLossBackward>)
Training loss:  tensor(46.6187, grad_fn

In [23]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 57.0777,  70.3703],
        [ 82.2895, 100.5627],
        [118.6441, 133.1053],
        [ 21.0746,  37.0522],
        [101.9694, 118.9911],
        [ 57.0777,  70.3703],
        [ 82.2895, 100.5627],
        [118.6441, 133.1053],
        [ 21.0746,  37.0522],
        [101.9694, 118.9911],
        [ 57.0777,  70.3703],
        [ 82.2895, 100.5627],
        [118.6441, 133.1053],
        [ 21.0746,  37.0522],
        [101.9694, 118.9911]], grad_fn=<AddmmBackward>)

In [24]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

Now we can define the model, optimizer and loss function exactly as before.

#Exercise 1:
 Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch library). You can optionally use sklearn (if you want)
#Exercise 2:
 Try Linear regression on same prediction data using Tensorflow

 

**Exercise 1**

In [25]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(inputs, targets, test_size=0.4, random_state=133)
lr.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [26]:
predicted = lr.predict(X_test)
print(predicted)
print(Y_test)

[[118.481804 133.03632 ]
 [ 56.878216  69.938446]
 [101.8928   119.0776  ]
 [ 21.12847   37.061092]
 [ 82.359604 100.90471 ]
 [118.481804 133.03632 ]]
tensor([[119., 133.],
        [ 56.,  70.],
        [103., 119.],
        [ 22.,  37.],
        [ 81., 101.],
        [119., 133.]])


**Exercise 2**

In [72]:
import numpy as np
import tensorflow as tf

inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [73]:
inputs = tf.Variable(inputs)
targets = tf.Variable(targets)
targets

<tf.Variable 'Variable:0' shape=(15, 2) dtype=float32, numpy=
array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]], dtype=float32)>

In [74]:
v = np.array([[34, 12], [90,43], [54, 30]], dtype='float32')
r = np.array([43, 21], dtype='float32')
v = tf.Variable(v)
r = tf.Variable(r)

In [75]:
predicted = inputs@v+r
print(meanse(predicted, targets))

tf.Tensor(116286070.0, shape=(), dtype=float32)


In [77]:
def model(m):
  return m@v+r
def meanse(a, b):
  return tf.reduce_mean(tf.square(a - b))
print(meanse(predicted, targets))

tf.Tensor(116286070.0, shape=(), dtype=float32)


In [78]:
epochs = 100
for i in range(epochs):
  with tf.GradientTape(persistent=True) as t:
    closs = meanse(targets, model(inputs))
  v1 = t.gradient(closs, v)
  r1 = t.gradient(closs, r)

  v.assign_sub(1e-4*v1)
  r.assign_sub(1e-4*r1)

In [79]:
model(inputs)

<tf.Tensor: shape=(15, 2), dtype=float32, numpy=
array([[ 60.925423,  70.77222 ],
       [102.03048 , 121.62281 ],
       [ 67.69624 ,  84.62628 ],
       [  3.445816,  21.62906 ],
       [155.0615  , 168.65588 ],
       [ 60.925423,  70.77222 ],
       [102.03048 , 121.62281 ],
       [ 67.69624 ,  84.62628 ],
       [  3.445816,  21.62906 ],
       [155.0615  , 168.65588 ],
       [ 60.925423,  70.77222 ],
       [102.03048 , 121.62281 ],
       [ 67.69624 ,  84.62628 ],
       [  3.445816,  21.62906 ],
       [155.0615  , 168.65588 ]], dtype=float32)>

In [80]:
targets

<tf.Variable 'Variable:0' shape=(15, 2) dtype=float32, numpy=
array([[ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.],
       [ 56.,  70.],
       [ 81., 101.],
       [119., 133.],
       [ 22.,  37.],
       [103., 119.]], dtype=float32)>