In [1]:
#Import scikit-learn dataset library
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

#Load dataset
iris = datasets.load_iris()

In [2]:
# print the names of the 13 features
print("Features: ", iris.feature_names)

# print the label type of wine(class_0, class_1, class_2)
print("Labels: ", iris.target_names)

# print data(feature)shape
iris.data.shape

Features:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Labels:  ['setosa' 'versicolor' 'virginica']


(150, 4)

In [3]:
#import the necessary module
from sklearn.model_selection import train_test_split

#split data set into train and test sets
data_train, data_test, target_train, target_test = train_test_split(iris.data,
                        iris.target, test_size = 0.30, random_state = 10)

In [4]:
import numpy as np
gnb = GaussianNB()

#Train the model using the training sets
gnb.fit(data_train, target_train)

#Predict the response for test dataset
target_pred = gnb.predict(data_test)

In [5]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 1.0


In [6]:
#Import confusion_matrix from scikit-learn metrics module for confusion_matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[14,  0,  0],
       [ 0, 17,  0],
       [ 0,  0, 14]])

In [7]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)

print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [1. 1. 1.]
recall: [1. 1. 1.]


**Exercise:**

**1) 1<=Rollnumber<=25:**
  #Task 1: Try the algo on Dataset1 - OneHotEncoding of features: and Train test Division 70%-30%

  #Task 2: Apply algorithm on digits dataset - LabelEncoding of features: and Train test Division 80%-20%

**2) 26<=Rollnumber<=50:**
  #Task 1: Try the algo on Dataset1 - LabelEncoding of features: and Train test Division 80%-20%

   #Task 2: Apply algorithm on breast cancer wisconsin dataset - One Hot Encoding of features: and Train test Division 60%-40%

**3) 51<=Rollnumber<=75:**
  #Task 1: Try the algo on Dataset2 - LabelEncoding of features: and Train test Division 90%-10%

  #Task 2: Apply algorithm on digits dataset - One Hot Encoding of features: and Train test Division 65%-35%

**4) 76<=Rollnumber<=100:**
  #Task 1: Try the algo on Dataset2 - OneHotEncoding of features: and Train test Division 75%-25%
  #Task 2: Apply algorithm on wine dataset - LabelEncoding of features: and Train test Division 80%-20%

**5) 101<=Rollnumber<=125:**
  #Task 1: Try the algo on Dataset3 - OneHotEncoding of features:and Train test Division 85%-15%
 #Task 2: Apply algorithm on wine dataset - LabelEncoding of features: and Train test Division 66%-34%

**6) 126<=Rollnumber + All with No RollNumbers:**
  #Task 1: Try the algo on Dataset3 - LabelEncoding of features:and Train test Division 95%-5%
  
 #Task 2: Apply algorithm on breast cancer wisconsin dataset - One Hot Encoding of features: and Train test Division 50%-50%



**Instruction for Task-1 & 2:**

i) Set Random state of model equals to your roll number (or last 2 digit of your id -if you don't have roll number)


**Questions: For Task - 1**

(1) What will be the value of Play, if Outlook is ’Rainy’, Temperature is ’Mild’, Humidity =’Normal’, and Wind = ’False’?

(2) What will be the value of Play, if Outlook is ’Sunny’, Temeprature is ’Cool’, Humidity =’High’, and Wind = ’True’?

(3) Accuracy , precision and recall of both Models?


**Task 1: Try the algo on Dataset3 - LabelEncoding of features:and Train test Division 95%-5%**

In [13]:
import numpy as np
import pandas as pd

data = pd.read_csv('Dataset3.csv')

#Examples
X = data.iloc[:, :-1].values 
  
# Class  
Y = data.iloc[:, -1].values

print(X,Y)


[['R' 'H' 'F' 1]
 ['R' 'H' 'T' 2]
 ['O' 'H' 'F' 1]
 ['R' 'M' 'F' 1]
 ['S' 'C' 'F' 1]
 ['O' 'C' 'T' 0]
 ['O' 'C' 'T' 1]
 ['R' 'M' 'F' 1]
 ['O' 'C' 'F' 0]
 ['S' 'M' 'F' 2]
 ['R' 'C' 'T' 2]
 ['O' 'M' 'T' 0]
 ['O' 'H' 'F' 1]
 ['S' 'M' 'T' 1]] [0 0 1 1 1 0 1 0 1 1 0 1 1 0]


In [20]:
from sklearn.preprocessing import LabelEncoder

#Label encoding for outlook, temp, wind
le = LabelEncoder()
for i in range(3):
  X[:, i] = le.fit_transform(X[:, i])
print(X)

[[1 1 0 1]
 [1 1 1 2]
 [0 1 0 1]
 [1 2 0 1]
 [2 0 0 1]
 [0 0 1 0]
 [0 0 1 1]
 [1 2 0 1]
 [0 0 0 0]
 [2 2 0 2]
 [1 0 1 2]
 [0 2 1 0]
 [0 1 0 1]
 [2 2 1 1]]


In [21]:
from sklearn.model_selection import train_test_split

#split data set into train and test sets
X_train, X_test, Y_train, Y_test = train_test_split(X,
                        Y, test_size = 0.05, random_state = 133)
print(X_train.shape)
print(Y_train.shape)

(13, 4)
(13,)


In [22]:
from sklearn.naive_bayes import GaussianNB

#Model training
gnb = GaussianNB()
gnb.fit(X_train, Y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [24]:

#Prediction
# 1)What will be the value of Play, if Outlook is 
#’Rainy’, Temperature is ’Mild’, Humidity =’Normal’, and Wind = ’False’?

print(gnb.predict([[1,2,0,1]]))

# 2)What will be the value of Play, if Outlook is 
#’Sunny’, Temeprature is ’Cool’, Humidity =’High’, and Wind = ’True’?

print(gnb.predict([[2,0,1,2]]))

[1]
[0]


In [25]:
predicted = gnb.predict(X_test)
print(predicted)

[0]


In [30]:
# 3) Accuracy , precision and recall of both Models?
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

print("Accuracy:", metrics.accuracy_score(Y_test, predicted))

confusion_matrix(Y_test, predicted)

precision = precision_score(Y_test, predicted, average=None, zero_division=1)
recall = recall_score(Y_test, predicted, average=None, zero_division=1)

print("Precision:", precision)
print("Recall:",recall)

Accuracy: 0.0
Precision: [0. 1.]
Recall: [1. 0.]


**Task 2: Apply algorithm on breast cancer wisconsin dataset - One Hot Encoding of features: and Train test Division 50%-50%**

In [32]:
data = pd.read_csv('Wisconsin.csv')

#Removing last column
data = data.iloc[:,1:32]
data.head()

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [34]:
X = data.iloc[:, 1:].values
Y = data.iloc[:, 0].values
print("X:",X)
print("Y:", Y)

X: [[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
Y: ['M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'B' 'B' 'B' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'B' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'M'
 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B'
 'M' 'M' 'B' 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'M' 'M' 'M' 'B' 'B'
 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B'
 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'B'
 'M' 'M' 'B' 'M' 'B' 'M' 'M' 'B' 'M' 'M' 'B' 'B' 'M' 'B' 'B' 'M' 'B' 'B'
 '

In [36]:
X_train, X_test, Y_train, Y_test = train_test_split(X,
                        Y, test_size = 0.5, random_state = 133)
print(X_train.shape, X_test.shape)

(284, 30) (285, 30)


In [37]:
#Model training
gnb = GaussianNB()
gnb.fit(X_train, Y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [38]:
#Prediction
predicted = gnb.predict(X_test)
print(predicted)

['M' 'B' 'B' 'M' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'M' 'M'
 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'M' 'B' 'M'
 'B' 'B' 'B' 'B' 'M' 'B' 'M' 'B' 'M' 'B' 'B' 'M' 'B' 'B' 'B' 'M' 'M' 'B'
 'B' 'M' 'M' 'M' 'M' 'B' 'M' 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'B'
 'B' 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'M' 'B' 'B' 'M' 'M' 'B' 'B'
 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'B' 'M' 'B'
 'B' 'M' 'M' 'B' 'M' 'B' 'B' 'M' 'B' 'M' 'B' 'B' 'M' 'B' 'B' 'B' 'B' 'B'
 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'M' 'M' 'B' 'M' 'M' 'M' 'B' 'B'
 'M' 'B' 'B' 'M' 'B' 'B' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'B' 'M' 'B' 'M' 'M'
 'B' 'M' 'B' 'B' 'B' 'M' 'B' 'B' 'M' 'B' 'B' 'M' 'B' 'M' 'B' 'B' 'B' 'M'
 'B' 'M' 'B' 'B' 'B' 'M' 'B' 'M' 'B' 'M' 'M' 'B' 'M' 'B' 'M' 'M' 'M' 'M'
 'M' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'M' 'M' 'B' 'M' 'B' 'B'
 'M' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'M' 'M' 'B' 'B' 'B' 'B' 'B'
 'B' 'B' 'M' 'M' 'B' 'B' 'M' 'M' 'M' 'M' 'B' 'M' 'M

In [39]:
confusion_matrix(Y_test, predicted)

array([[164,   6],
       [ 12, 103]])

In [41]:
print("Accuracy:", metrics.accuracy_score(Y_test, predicted)) 
precision = precision_score(Y_test, predicted, average=None)
recall = recall_score(Y_test, predicted, average=None)

print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

Accuracy: 0.9368421052631579
precision: [0.93181818 0.94495413]
recall: [0.96470588 0.89565217]
